name: echo

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
  workflow_dispatch:

env:
  REPO_NAME1: gh-actions1

jobs:
  Run-echo:
    name: Run echo
    runs-on: ubuntu-latest
    env:
      REPO_NAME2: gh-actions2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run $
        env:
          REPO_NAME3: gh-actions3
        run: |
          echo "$REPO_NAME1"
          echo "$REPO_NAME2"
          echo "$REPO_NAME3"

      - name: Run ${}
        env:
          REPO_NAME3: gh-actions3
        run: |
          echo "${REPO_NAME1}"
          echo "${REPO_NAME2}"
          echo "${REPO_NAME3}"
